# Page settings

baseurl = "http://danielendr.es/about/"
languageCode = "en-us"
title = "Daniel Endres - Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Resume of Daniel Endres, PTM lead bringing Gemini into cars"
    author = "Daniel Endres"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "daen-2.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Daniel Endres"
        tagline = "PTM Lead @Google | Bringing Gemini into cars"
        avatar = "me.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: contact@zwischenablage.org"
        title = "contact@zwischenablage.org"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "https://zwischenablage.github.io/me/"
        title = "zwischenablage.github.io/me"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/daniel-endres/"
        title = "linkedin.com/in/daniel-endres/"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/zwischenablage"
        title = "github.com/zwischenablage"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/zwischenablage"
        title = "@zwischenablage"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc in Computer Science - Dipl.-Inf. (FH)"
        college = "Augsburg University of Applied Sciences"
        dates = "2002 - 2007"

        [[params.education.list]]
        degree = "M.A. in Interactive Media Systems"
        college = "Augsburg University of Applied Sciences"
        dates = "2007 - 2008"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "German"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"


    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Photography"

        [[params.interests.list]]
        interest = "Guitar"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "I'm the lead Partner Technology Manager at Google, currently focused on bringing Gemini into cars. I embed with automotive partners to turn frontier AI into production-grade experiences, operate calmly in safety-critical ambiguity, and align research and product teams with OEM realities to deliver measurable improvements across global programs."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Partner Technology Manager - Gemini in Cars"
        dates = "Jan 2022 - Present"
        company = "Google, Munich"
        details = """- Steering **Gemini** from functional prototypes toward staged rollouts, coordinating global automotive launch teams under urgent timelines to prepare millions of vehicles for launch.
- Produced end-to-end sample integrations, technical guides, and quality dashboards across Android Automotive applications to help partners integrate Gemini, monitor quality, and scale deployments.
- Drove requirement alignment between partner roadmaps and Gemini product, translating field feedback into prioritized updates and enforcing quality and safety gates with leadership stakeholders.
- Curated the Gemini launch toolkit—certification guides, FAQs, help-center material, and communications—and ran weekly readiness forums keeping Engineering, Product, and Business teams on track.
- Led Gemini/Assistant operational excellence by restoring KPI visibility with an offline scoring tool, mentoring first-line specialists, and documenting triage playbooks now standard across the partner engineering organization.
- Orchestrated high-profile mobility demos, producing quality dashboards, runbooks, and vehicle setups that showcased Gemini and companion multimodal experiences to executives and external audiences."""
               [[params.jobs.list]]
        position = "Software Architect - IVI Platform / Android Automotive"
        dates = "Mar 2019 - Dec 2022"
        company = "Audi AG, Ingolstadt"
        details = "Owned the architecture for the next-generation **IVI platform** built on Android Automotive. Provided system blueprints, governance, and tooling that enabled cross-brand reuse within the Volkswagen Group. Partnered closely with design, product, and supplier teams to deliver high-performance multimedia, navigation, and connectivity experiences."
        [[params.jobs.list]]
        position = "Senior Project Manager - Acoustics"
        dates = "2016 - Feb 2019"
        company = "Nuance Communications GmbH, Ulm"
        details = "Led cross-regional programs for **automotive acoustics and speech enhancement**, acting as the primary interface for OEM and Tier 1 partners. Managed contracts, delivery schedules, and escalations while guiding technical decisions on architecture, algorithm integration, and performance validation."
        [[params.jobs.list]]
        position = "Technical Project Lead / Software Architect - Multimedia"
        dates = "2012 - 2015"
        company = "e.solutions GmbH, Ingolstadt"
        details = "Directed the integration of **Apple CarPlay**, **Android Auto**, and in-vehicle streaming services into Audi infotainment products. Defined multimedia system architecture, coordinated supplier deliverables, and established validation processes for Blu-ray Disc playback and passenger video streaming."

        [[params.jobs.list]]
        position = "Senior Software Engineer - Multimedia"
        dates = "2010 - 2012"
        company = "e.solutions GmbH, Ingolstadt"
        details = "Developed multimedia applications for the **in-vehicle infotainment** platform used across Audi and the wider Volkswagen Group. Delivered playback pipelines for diverse audio and video formats, optimized performance for embedded hardware, and collaborated with UX teams on feature rollouts."

        [[params.jobs.list]]
        position = "Linux OS Software Developer"
        dates = "2008 - 2010"
        company = "Igel GmbH, Augsburg"
        details = "Built core components of a custom **Linux operating system** for thin clients, including kernel and network drivers, X11 server extensions, and access-control capabilities. Established tooling that improved release throughput and diagnostic coverage."

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Forward Deployed Delivery"
        level = "100%"

        [[params.skills.list]]
        skill = "LLM Product Integration"
        level = "95%"

        [[params.skills.list]]
        skill = "Android Automotive Platforms"
        level = "95%"

        [[params.skills.list]]
        skill = "Full-Stack Prototyping (Python/JS)"
        level = "85%"

        [[params.skills.list]]
        skill = "Cloud & Edge Architecture"
        level = "85%"

        [[params.skills.list]]
        skill = "Program Leadership"
        level = "90%"

        [[params.skills.list]]
        skill = "Partner Engineering"
        level = "95%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
